name: API Smoke

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting API smoke test..."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Probe endpoints (HTTPS first, then HTTP)
        env:
          BASE_URL: https://apis.data.go.kr/B551011/KorService1
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
        run: |
          import requests, sys, os
          base_url = os.environ["BASE_URL"]
          svc_key = os.environ["SERVICE_KEY"]

          url = f"{base_url}/areaBasedList1"
          params = {
              "MobileOS": "ETC",
              "MobileApp": "SmartTravelPlanner",
              "_type": "json",
              "areaCode": "51",
              "sigunguCode": "51130",
              "listYN": "Y",
              "arrange": "A",
              "numOfRows": 1,
              "pageNo": 1,
              "serviceKey": svc_key
          }

          r = requests.get(url, params=params, timeout=10)
          try:
              data = r.json()
          except Exception as e:
              print("Invalid JSON:", e)
              sys.exit(1)

          if r.status_code != 200 or "response" not in data:
              print("No candidate returned valid JSON")
              sys.exit(1)

          print("✅ API is reachable and returned valid JSON")
        shell: python
